import { useState, useContext, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { AuthContext } from '../../context/AuthContext';
import toast from 'react-hot-toast';
import { validatePGEmail } from '../../utils/emailValidator';

const LoginPage = () => {
  const [activeTab, setActiveTab] = useState('login');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [agreeTerms, setAgreeTerms] = useState(false);
  const [emailValidation, setEmailValidation] = useState(null);
  const [isLoading, setIsLoading] = useState(false);
  const [fullName, setFullName] = useState('');
  const [username, setUsername] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [isAutoGenerated, setIsAutoGenerated] = useState(false);
  const { login, register } = useContext(AuthContext); // ✅ Use AuthContext methods
  const navigate = useNavigate();

  useEffect(() => {
    localStorage.removeItem('pg_user');
  }, []);

  const handleEmailChange = (e) => {
    const newEmail = e.target.value;
    setEmail(newEmail);
    if (newEmail) {
      setEmailValidation(validatePGEmail(newEmail));
    } else {
      setEmailValidation(null);
    }
  };

  // ✅ Function to generate random password
  const generateRandomPassword = () => {
    const length = 10;
    const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*";
    let generatedPassword = "";
    for (let i = 0; i < length; i++) {
      const randomIndex = Math.floor(Math.random() * charset.length);
      generatedPassword += charset[randomIndex];
    }
    return generatedPassword;
  };

  // ✅ Handle auto-generate password
  const handleGeneratePassword = () => {
    const newPassword = generateRandomPassword();
    setPassword(newPassword);
    setConfirmPassword(newPassword);
    setIsAutoGenerated(true);
    toast.success('🔑 Strong password generated!');
  };

  // ✅ Handle manual password change
  const handlePasswordChange = (e) => {
    setPassword(e.target.value);
    setIsAutoGenerated(false);
  };

  const handleConfirmPasswordChange = (e) => {
    setConfirmPassword(e.target.value);
  };

  // ✅ Register with AuthContext (Local Storage)
  const handleCreateAccount = () => {
    if (!emailValidation?.valid) {
      toast.error('Please enter a valid PG student email');
      return;
    }

    if (!agreeTerms) {
      toast.error('Please accept Terms & Privacy Policy');
      return;
    }

    if (password !== confirmPassword) {
      toast.error('Passwords do not match!');
      return;
    }

    if (password.length < 6) {
      toast.error('Password must be at least 6 characters');
      return;
    }

    setIsLoading(true);
    
    // ✅ Use AuthContext register method (local storage)
    const result = register(email, password, fullName, username);

    if (result.success) {
      toast.success('✅ Account created successfully!');
      // ✅ Navigate based on user role
      const user = result.user;
      navigate(`/${user.role}-dashboard`);
    } else {
      toast.error(result.message || 'Failed to create account');
    }
    
    setIsLoading(false);
  };

  // ✅ Login with AuthContext (Local Storage)
  const handleLogin = (e) => {
    e.preventDefault();

    if (!email || !password) {
      toast.error('Please enter email and password');
      return;
    }

    setIsLoading(true);
    
    // ✅ Use AuthContext login method (local storage)
    const result = login(email, password);

    if (result.success) {
      const user = result.user;
      toast.success(`Welcome ${user.name}!`);
      navigate(`/${user.role}-dashboard`);
    } else {
      toast.error(result.message || 'Invalid email or password');
    }
    
    setIsLoading(false);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-oric-navy via-oric-blue to-oric-dark-navy flex items-center justify-center p-4">
      <div className="w-full max-w-5xl">
        <div className="bg-white rounded-2xl shadow-2xl overflow-hidden">
          
          <div className="flex flex-col md:flex-row">
            
            {/* LEFT COLUMN */}
            <div className="w-full md:w-2/5 bg-gradient-to-br from-oric-navy via-oric-blue to-oric-dark-navy p-8 md:p-10 flex flex-col items-center justify-center text-white">
              <div className="mb-5">
                <img 
                  src="https://media.licdn.com/dms/image/v2/D4D0BAQGxKTAJAKoPSA/company-logo_200_200/B4DZfo9EQtHkAU-/0/1751960012437?e=2147483647&v=beta&t=yyCBiw0f0esKh9ZHFOJkIWUmS-IJWZ7J1ZqiL1ZnVV4"
                  alt="ORIC MUET"
                  className="w-20 h-20 object-contain rounded-2xl shadow-2xl bg-white p-2.5"
                  onError={(e) => {
                    e.target.onerror = null;
                    e.target.src = "https://oric.muet.edu.pk/assets/ab1-Cere0Ipv.png";
                  }}
                />
              </div>
              <h1 className="text-2xl md:text-3xl font-bold text-center">MUET ORIC</h1>
              <p className="text-oric-light-blue text-center mt-1 text-xs md:text-sm">Research & Innovation Portal</p>
              <div className="mt-6 w-full max-w-xs">
                <div className="flex items-center gap-3 mb-3">
                  <div className="w-7 h-7 rounded-full bg-oric-gold text-oric-navy flex items-center justify-center font-bold text-xs">1</div>
                  <span className="text-white/80 text-sm">Account Setup</span>
                </div>
                <div className="flex items-center gap-3">
                  <div className="w-7 h-7 rounded-full bg-white/20 text-white flex items-center justify-center font-bold text-xs">2</div>
                  <span className="text-white/60 text-sm">University Info</span>
                </div>
              </div>
              <div className="mt-6 flex gap-3">
                <div className="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center text-xl">🎓</div>
                <div className="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center text-xl">🔬</div>
                <div className="w-10 h-10 rounded-full bg-white/10 flex items-center justify-center text-xl">💡</div>
              </div>
              <p className="text-oric-light-blue/60 text-[10px] mt-6 text-center">Postgraduate students only (ME/PhD)</p>
            </div>

            {/* RIGHT COLUMN */}
            <div className="w-full md:w-3/5 p-6 md:p-8">
              <div className="text-center mb-5">
                <h2 className="text-xl font-bold text-oric-navy">MUET Registration</h2>
                <p className="text-gray-500 text-xs">Postgraduate students only</p>
              </div>

              <div className="flex border-b border-gray-200 mb-5">
                <button
                  onClick={() => setActiveTab('login')}
                  className={`flex-1 py-2 text-sm font-medium transition-all ${
                    activeTab === 'login'
                      ? 'text-white bg-oric-royal border-b-2 border-oric-gold'
                      : 'text-gray-400 hover:text-white hover:bg-oric-blue/30'
                  }`}
                >
                  Sign In
                </button>
                <button
                  onClick={() => {
                    setActiveTab('register');
                    setEmail('');
                    setPassword('');
                    setFullName('');
                    setUsername('');
                    setConfirmPassword('');
                    setIsAutoGenerated(false);
                  }}
                  className={`flex-1 py-2 text-sm font-medium transition-all ${
                    activeTab === 'register'
                      ? 'text-oric-royal border-b-2 border-oric-gold'
                      : 'text-gray-500 hover:text-oric-navy'
                  }`}
                >
                  Create Account
                </button>
              </div>

              {activeTab === 'login' && (
                <form onSubmit={handleLogin} className="space-y-3">
                  <div>
                    <label className="block text-sm font-medium text-oric-dark-gray mb-1">Email Address</label>
                    <input
                      type="email"
                      value={email}
                      onChange={handleEmailChange}
                      className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oric-royal outline-none text-sm"
                      placeholder="23meCS008@students.muet.edu.pk"
                      required
                    />
                    {emailValidation && emailValidation.valid && (
                      <p className="text-xs text-oric-success mt-1">✅ {emailValidation.roleName}</p>
                    )}
                    {email && emailValidation && !emailValidation.valid && (
                      <p className="text-xs text-oric-danger mt-1">❌ {emailValidation.message}</p>
                    )}
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-oric-dark-gray mb-1">Password</label>
                    <div className="relative">
                      <input
                        type={showPassword ? 'text' : 'password'}
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oric-royal outline-none pr-10 text-sm"
                        placeholder="Enter your password"
                        required
                      />
                      <button
                        type="button"
                        onClick={() => setShowPassword(!showPassword)}
                        className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-500"
                      >
                        {showPassword ? '🙈' : '👁️'}
                      </button>
                    </div>
                  </div>

                  <button
                    type="submit"
                    disabled={isLoading}
                    className="w-full bg-oric-royal text-white py-2 rounded-lg hover:bg-oric-blue transition font-medium text-sm disabled:opacity-50"
                  >
                    {isLoading ? 'Signing in...' : 'Sign In'}
                  </button>

                  <p className="text-center text-sm text-gray-500">
                    Don't have an account?{' '}
                    <button type="button" onClick={() => setActiveTab('register')} className="text-oric-royal font-medium hover:underline">
                      Create account
                    </button>
                  </p>
                </form>
              )}

              {activeTab === 'register' && (
                <div className="space-y-3">
                  <div className="text-center mb-1">
                    <h2 className="text-lg font-semibold text-oric-navy">MUET ORIC</h2>
                    <p className="text-xs text-gray-500">Research & Innovation Portal</p>
                  </div>

                  <div className="space-y-2.5">
                    <div>
                      <label className="block text-sm font-medium text-oric-dark-gray mb-1">Full Name</label>
                      <input
                        type="text"
                        value={fullName}
                        onChange={(e) => setFullName(e.target.value)}
                        className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oric-royal outline-none text-sm"
                        placeholder="Enter your full name"
                      />
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-oric-dark-gray mb-1">Username</label>
                      <input
                        type="text"
                        value={username}
                        onChange={(e) => setUsername(e.target.value)}
                        className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oric-royal outline-none text-sm"
                        placeholder="Choose a username"
                      />
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-oric-dark-gray mb-1">MUET Email</label>
                      <input
                        type="email"
                        value={email}
                        onChange={handleEmailChange}
                        className={`w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-oric-royal outline-none text-sm ${
                          emailValidation?.valid ? 'border-oric-success bg-green-50' : 
                          emailValidation && !emailValidation.valid ? 'border-oric-danger bg-red-50' : 'border-gray-300'
                        }`}
                        placeholder="23meCS008@students.muet.edu.pk"
                      />
                      {emailValidation?.valid && (
                        <p className="text-xs text-oric-success mt-1">✅ Valid {emailValidation.roleName}</p>
                      )}
                      {emailValidation && !emailValidation.valid && (
                        <p className="text-xs text-oric-danger mt-1">❌ {emailValidation.message}</p>
                      )}
                      <div className="mt-1 p-1.5 bg-oric-light-blue/30 rounded-lg">
                        <p className="text-[9px] text-oric-navy">📝 Accepted: Master's (me) & PhD (phd)</p>
                      </div>
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-oric-dark-gray mb-1">
                        Create Password
                        <button
                          type="button"
                          onClick={handleGeneratePassword}
                          className="ml-2 px-2 py-0.5 text-xs bg-oric-blue text-white rounded hover:bg-oric-navy transition"
                        >
                          🔑 Auto-Generate
                        </button>
                      </label>
                      <div className="relative">
                        <input
                          type={showPassword ? 'text' : 'password'}
                          value={password}
                          onChange={handlePasswordChange}
                          className={`w-full px-4 py-2 border rounded-lg focus:ring-2 focus:ring-oric-royal outline-none pr-10 text-sm ${
                            isAutoGenerated ? 'border-oric-success bg-green-50' : 'border-gray-300'
                          }`}
                          placeholder="Min 6 characters"
                        />
                        <button
                          type="button"
                          onClick={() => setShowPassword(!showPassword)}
                          className="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-500"
                        >
                          {showPassword ? '🙈' : '👁️'}
                        </button>
                        {isAutoGenerated && (
                          <span className="absolute right-10 top-1/2 transform -translate-y-1/2 text-xs text-oric-success font-medium">
                            🔒 Auto
                          </span>
                        )}
                      </div>
                      {isAutoGenerated && (
                        <p className="text-xs text-oric-success mt-1">✅ Strong password generated (copy it now!)</p>
                      )}
                    </div>

                    <div>
                      <label className="block text-sm font-medium text-oric-dark-gray mb-1">Confirm Password</label>
                      <input
                        type="password"
                        value={confirmPassword}
                        onChange={handleConfirmPasswordChange}
                        className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-oric-royal outline-none text-sm"
                        placeholder="Confirm your password"
                      />
                      {password && confirmPassword && password !== confirmPassword && (
                        <p className="text-xs text-oric-danger mt-1">❌ Passwords do not match</p>
                      )}
                      {password && confirmPassword && password === confirmPassword && (
                        <p className="text-xs text-oric-success mt-1">✅ Passwords match</p>
                      )}
                    </div>
                  </div>

                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={agreeTerms}
                      onChange={(e) => setAgreeTerms(e.target.checked)}
                      className="w-4 h-4 text-oric-royal rounded"
                    />
                    <span className="text-sm text-gray-600">I agree to the Terms & Privacy Policy</span>
                  </label>

                  <button
                    type="button"
                    onClick={handleCreateAccount}
                    disabled={!emailValidation?.valid || !agreeTerms || isLoading}
                    className="w-full bg-oric-gold text-oric-navy py-2 rounded-lg hover:bg-oric-dark-gold transition font-medium text-sm disabled:opacity-50"
                  >
                    {isLoading ? 'Creating Account...' : 'Continue'}
                  </button>

                  <p className="text-center text-sm text-gray-500">
                    Already have an account?{' '}
                    <button type="button" onClick={() => setActiveTab('login')} className="text-oric-royal font-medium hover:underline">
                      Sign in
                    </button>
                  </p>
                </div>
              )}
            </div>
          </div>

          <div className="bg-oric-navy px-6 py-2.5 text-center">
            <p className="text-[10px] text-oric-light-blue">
              © 2024 ORIC MUET Office of Research, Innovation & Commercialization
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default LoginPage;