/* eslint-disable react-refresh/only-export-components */
import { createContext, useState, useEffect } from 'react';
import toast from 'react-hot-toast';
import { validatePGEmail, getNameFromEmail } from '../utils/emailValidator';

export const AuthContext = createContext();

export const AuthProvider = ({ children }) => {
  const [user, setUser] = useState(null);
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Use a function to avoid direct setState in effect warning
    const loadUser = () => {
      const stored = localStorage.getItem('pg_user');
      if (stored) {
        try {
          const parsedUser = JSON.parse(stored);
          setUser(parsedUser);
          setIsAuthenticated(true);
        } catch (error) {
          console.error('Error parsing user data:', error);
        }
      }
      setLoading(false);
    };
    loadUser();
  }, []);

  // ✅ Function to generate random password
  const generateRandomPassword = () => {
    const length = 10;
    const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*";
    let generatedPassword = "";
    for (let i = 0; i < length; i++) {
      const randomIndex = Math.floor(Math.random() * charset.length);
      generatedPassword += charset[randomIndex];
    }
    return generatedPassword;
  };

  const register = (email, password, fullName, username) => {
    const validation = validatePGEmail(email);
    if (!validation.valid) {
      toast.error(validation.message);
      return { success: false, message: validation.message };
    }

    const users = JSON.parse(localStorage.getItem('pg_users') || '[]');
    const existingUser = users.find(u => u.email === email);
    if (existingUser) {
      toast.error('❌ Account already exists! Please login.');
      return { success: false, message: 'Account already exists' };
    }

    const newUser = {
      id: Date.now(),
      email: email,
      name: fullName || getNameFromEmail(email),
      username: username || email.split('@')[0],
      password: password,
      role: validation.role,
      roleName: validation.roleName,
      year: validation.year,
      department: validation.department,
      rollNumber: validation.id,
      firstLogin: true
    };

    users.push(newUser);
    localStorage.setItem('pg_users', JSON.stringify(users));
    localStorage.setItem('pg_user', JSON.stringify(newUser));
    
    setUser(newUser);
    setIsAuthenticated(true);
    toast.success(`✅ Account created! Welcome ${newUser.name}`);
    return { success: true, user: newUser };
  };

  // ✅ Register with auto-generated password
  const registerWithAutoPassword = (email, fullName, username) => {
    const validation = validatePGEmail(email);
    if (!validation.valid) {
      toast.error(validation.message);
      return { success: false, message: validation.message };
    }

    const users = JSON.parse(localStorage.getItem('pg_users') || '[]');
    const existingUser = users.find(u => u.email === email);
    if (existingUser) {
      toast.error('❌ Account already exists! Please login.');
      return { success: false, message: 'Account already exists' };
    }

    // ✅ Generate random password
    const generatedPassword = generateRandomPassword();

    const newUser = {
      id: Date.now(),
      email: email,
      name: fullName || getNameFromEmail(email),
      username: username || email.split('@')[0],
      password: generatedPassword,
      role: validation.role,
      roleName: validation.roleName,
      year: validation.year,
      department: validation.department,
      rollNumber: validation.id,
      firstLogin: true,
      isAutoGenerated: true // ✅ Flag to identify auto-generated password
    };

    users.push(newUser);
    localStorage.setItem('pg_users', JSON.stringify(users));
    localStorage.setItem('pg_user', JSON.stringify(newUser));
    
    setUser(newUser);
    setIsAuthenticated(true);
    toast.success(`✅ Account created! Your password: ${generatedPassword}`);
    return { success: true, user: newUser, password: generatedPassword };
  };

  const login = (email, password) => {
    const validation = validatePGEmail(email);
    if (!validation.valid) {
      toast.error(validation.message);
      return { success: false, message: validation.message };
    }

    const users = JSON.parse(localStorage.getItem('pg_users') || '[]');
    const userData = users.find(u => u.email === email);

    if (!userData) {
      toast.error('❌ No account found. Please register first.');
      return { success: false, message: 'Account not found' };
    }

    if (userData.password !== password) {
      toast.error('❌ Invalid password!');
      return { success: false, message: 'Invalid password' };
    }

    userData.lastLogin = new Date().toISOString();
    localStorage.setItem('pg_users', JSON.stringify(users));
    localStorage.setItem('pg_user', JSON.stringify(userData));

    setUser(userData);
    setIsAuthenticated(true);
    toast.success(`Welcome ${userData.name}!`);
    return { success: true, user: userData };
  };

  const logout = () => {
    setUser(null);
    setIsAuthenticated(false);
    localStorage.removeItem('pg_user');
    toast.success('Logged out successfully');
  };

  return (
    <AuthContext.Provider value={{ 
      user, 
      isAuthenticated, 
      loading, 
      login, 
      register, 
      logout,
      registerWithAutoPassword, // ✅ New method for auto-generated password
      generateRandomPassword // ✅ Expose generator if needed
    }}>
      {children}
    </AuthContext.Provider>
  );
};